
import streamlit as st
from data.utils import t, get_persona, guard

st.sidebar.title("Benew")
st.sidebar.page_link("app.py", label=t("menu_home"))
st.sidebar.page_link("pages/00_Login.py", label=t("menu_login"))
st.sidebar.page_link("pages/01_Persona.py", label=t("menu_persona"))
st.sidebar.page_link("pages/10_Banking.py", label=t("menu_banking"))
st.sidebar.page_link("pages/20_Insurance.py", label=t("menu_insurance"))
st.sidebar.page_link("pages/30_Healthcare.py", label=t("menu_healthcare"))
st.sidebar.page_link("pages/40_Taxation.py", label=t("menu_taxation"))
st.sidebar.page_link("pages/50_Housing.py", label=t("menu_housing"))
st.sidebar.page_link("pages/60_Transport.py", label=t("menu_transport"))
st.sidebar.page_link("pages/70_Work.py", label=t("menu_work"))
st.sidebar.page_link("pages/80_Life.py", label=t("menu_life"))
st.sidebar.page_link("pages/90_Tools.py", label=t("menu_tools"))
st.sidebar.page_link("pages/91_Glossary.py", label=t("menu_glossary"))
st.sidebar.page_link("pages/92_Plan30.py", label=t("menu_plan"))
st.sidebar.page_link("pages/93_Compare.py", label=t("menu_compare"))
st.sidebar.page_link("pages/94_Export.py", label=t("menu_export"))

guard()
st.title(t("menu_plan"))
p = get_persona()
st.write("### Semaine 1")
st.markdown("- Ouvrir un **compte courant** + activer l’app bancaire.")
st.markdown("- Demander la **Carte Vitale** / créer le compte **Ameli** (si non fait).")
st.markdown("- Chercher un logement / préparer **dossier complet** (ID, revenus).")
st.write("### Semaine 2")
st.markdown("- Ouvrir un **Livret A/LDDS** et commencer à épargner.")
st.markdown("- Souscrire **assurance habitation** (si location).")
st.markdown("- **Mutuelle** : d’entreprise si salarié, sinon individuelle.")
st.write("### Semaine 3")
st.markdown("- Abonnement transport (Navigo/ville) / vérifier réduction jeunes/solidaires.")
st.markdown("- Internet fixe si besoin (éligibilité fibre).")
st.write("### Semaine 4")
st.markdown("- Déclarer son espace **impots.gouv.fr** et vérifier le **prélèvement à la source**.")
st.markdown("- Vérifier paie (SMIC / brut‑net), congés, mutuelle d’entreprise.")
st.caption(t("disclaimer"))
